import type { CSSProperties, ReactNode } from "react";

/**
 * Grid — the 12-column / 24px-gutter substrate (§6). Asymmetry is the house
 * style: content lives on cols 1–7, labels hang in the left margin, the right
 * side is deliberate negative space, and the section motif lands on the 5/12
 * line. Never center body prose. Place children with <Col> (or col-* classes).
 */
export function Grid({
  className = "",
  children,
}: {
  className?: string;
  children: ReactNode;
}) {
  return (
    <div className={`grid grid-cols-12 gap-x-6 ${className}`.trim()}>{children}</div>
  );
}

/**
 * Col — a span on the 12-col grid. `span` columns wide, optional `start`.
 * Defaults stack full-width below `md` so the asymmetry is a desktop decision,
 * never a cramped-mobile one.
 */
export function Col({
  span = 12,
  start,
  mdSpan,
  mdStart,
  className = "",
  children,
}: {
  span?: number;
  start?: number;
  mdSpan?: number;
  mdStart?: number;
  className?: string;
  children: ReactNode;
}) {
  // Use CSS custom props → grid-column so any 1–12 value works without a
  // Tailwind safelist (arbitrary col spans aren't all generated by default).
  const style = {
    "--col-span": span,
    "--col-start": start ?? "auto",
    "--col-span-md": mdSpan ?? span,
    "--col-start-md": mdStart ?? start ?? "auto",
  } as CSSProperties;
  return (
    <div className={`hz-col ${className}`.trim()} style={style}>
      {children}
    </div>
  );
}
